# Generated by Django 4.2.29 on 2026-04-10 09:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_productimage_caption'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='donation',
        ),
        migrations.RemoveField(
            model_name='order',
            name='gift_wrapping',
        ),
        migrations.RemoveField(
            model_name='order',
            name='handling_charge',
        ),
    ]
